/*
 * This file is generated by jOOQ.
*/
package com.mt.demo.db;


import com.mt.demo.db.tables.DICTIONARY_TABLE;
import com.mt.demo.db.tables.USERS_TABLE;
import com.mt.demo.db.tables.USER_TABLE;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in person_service_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 字典表
     */
    public static final DICTIONARY_TABLE DICTIONARY = com.mt.demo.db.tables.DICTIONARY_TABLE.DICTIONARY;

    /**
     * The table <code>person_service_schema.sys_user</code>.
     */
    public static final USER_TABLE USER = com.mt.demo.db.tables.USER_TABLE.USER;

    /**
     * The table <code>person_service_schema.users</code>.
     */
    public static final USERS_TABLE USERS = com.mt.demo.db.tables.USERS_TABLE.USERS;
}
