/*
 * This file is generated by jOOQ.
*/
package com.mt.demo.db.tables.daos;


import com.mt.demo.db.tables.USER_TABLE;
import com.mt.demo.db.tables.pojos.User;
import com.mt.demo.db.tables.records.UserRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDaoSupper extends DAOImpl<UserRecord, User, Long> {

    /**
     * Create a new UserDaoSupper without any configuration
     */
    public UserDaoSupper() {
        super(USER_TABLE.USER, User.class);
    }

    /**
     * Create a new UserDaoSupper with an attached configuration
     */
    public UserDaoSupper(Configuration configuration) {
        super(USER_TABLE.USER, User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<User> fetchById(Long... values) {
        return fetch(USER_TABLE.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public User fetchOneById(Long value) {
        return fetchOne(USER_TABLE.USER.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<User> fetchByName(String... values) {
        return fetch(USER_TABLE.USER.NAME, values);
    }

    /**
     * Fetch records that have <code>id_card_number IN (values)</code>
     */
    public List<User> fetchByIdCardNumber(String... values) {
        return fetch(USER_TABLE.USER.ID_CARD_NUMBER, values);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<User> fetchByGender(Integer... values) {
        return fetch(USER_TABLE.USER.GENDER, values);
    }

    /**
     * Fetch records that have <code>phone_no IN (values)</code>
     */
    public List<User> fetchByPhoneNo(String... values) {
        return fetch(USER_TABLE.USER.PHONE_NO, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<User> fetchByEmail(String... values) {
        return fetch(USER_TABLE.USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<User> fetchByStatus(Integer... values) {
        return fetch(USER_TABLE.USER.STATUS, values);
    }

    /**
     * Fetch records that have <code>department IN (values)</code>
     */
    public List<User> fetchByDepartment(String... values) {
        return fetch(USER_TABLE.USER.DEPARTMENT, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<User> fetchByCreateTime(Timestamp... values) {
        return fetch(USER_TABLE.USER.CREATE_TIME, values);
    }
}
